#!/usr/bin/env bash
# One-time local setup to stop the macOS keychain from re-prompting for comail's
# stored secrets on every `tauri dev` / `cargo` rebuild.
#
# WHY: unsigned/ad-hoc debug builds get a new code signature (CDHash) on every
# compile. The login keychain ties its "Always Allow" grant to a specific
# signature, so each rebuild looks like a brand-new app and you get asked again.
#
# FIX: create a stable, self-signed "comail-dev" code-signing identity and wire
# up a cargo `runner` that signs each debug build with it + a fixed identifier.
# Every rebuild then presents the SAME signature, so the grant sticks.
#
# Run once:   bash src-tauri/scripts/macos-dev-cert.sh
# Safe to re-run (idempotent).
set -euo pipefail

if [ "$(uname)" != "Darwin" ]; then
  echo "This script is macOS-only." >&2
  exit 1
fi

IDENTITY="comail-dev"
KEYCHAIN="$HOME/Library/Keychains/login.keychain-db"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SIGN_SCRIPT="$SCRIPT_DIR/macos-dev-sign.sh"
CARGO_DIR="$SCRIPT_DIR/../.cargo"
CARGO_CONFIG="$CARGO_DIR/config.toml"

chmod +x "$SIGN_SCRIPT"

create_identity() {
  if security find-certificate -c "$IDENTITY" "$KEYCHAIN" >/dev/null 2>&1; then
    echo "  ✓ '$IDENTITY' identity already present"
    return
  fi
  echo "  • creating self-signed '$IDENTITY' code-signing identity"
  local tmp
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' RETURN

  openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "$tmp/key.pem" -out "$tmp/cert.pem" -days 3650 \
    -subj "/CN=$IDENTITY" \
    -addext "extendedKeyUsage=codeSigning" \
    -addext "keyUsage=critical,digitalSignature" >/dev/null 2>&1

  # A throwaway transfer password: Apple's PKCS12 importer fails MAC
  # verification on truly empty-password bundles, so use a non-empty one just
  # for the openssl -> keychain handoff.
  local p12pass="comail-dev"
  openssl pkcs12 -export -inkey "$tmp/key.pem" -in "$tmp/cert.pem" \
    -name "$IDENTITY" -out "$tmp/id.p12" -passout "pass:$p12pass" >/dev/null 2>&1

  # -A: let any tool (codesign) use this throwaway *dev signing* key without a
  # separate prompt. It signs nothing sensitive, so allow-all is fine here.
  security import "$tmp/id.p12" -k "$KEYCHAIN" -P "$p12pass" -A \
    -T /usr/bin/codesign -T /usr/bin/security >/dev/null
}

write_cargo_config() {
  mkdir -p "$CARGO_DIR"
  # Absolute runner path: cargo resolves relative runners against the cwd, which
  # would break `cargo test` run from elsewhere. This file is gitignored — it's
  # a per-developer local override, so a machine-specific path is correct.
  cat >"$CARGO_CONFIG" <<EOF
# Generated by scripts/macos-dev-cert.sh — local dev only, gitignored.
# Signs each debug build with the stable "comail-dev" identity so the macOS
# keychain stops re-prompting for comail's secrets. Delete this file (and the
# 'comail-dev' cert in Keychain Access) to revert.
[target.'cfg(target_os = "macos")']
runner = "$SIGN_SCRIPT"
EOF
  echo "  ✓ wrote $CARGO_CONFIG"
}

echo "Setting up local dev code-signing for comail:"
create_identity
write_cargo_config
cat <<'EOF'

Done. Next steps:
  1. Run the app as usual:  pnpm tauri dev
  2. On the first launch you'll get ONE keychain prompt for comail's secrets —
     click **Always Allow**. (The old ad-hoc grant doesn't match the new stable
     signature, so it re-asks exactly once.)
  3. After that, rebuilds keep the same signature and you won't be prompted again.

To revert: delete src-tauri/.cargo/config.toml and remove the 'comail-dev'
certificate from Keychain Access.
EOF
